version: "3.9"

services:
  # start server
  server:
    image: aemdesign/java-buildpack:jdk11
    command: /bin/bash -l /build/source/scripts/automation-test.sh
    working_dir: /build/source
    volumes:
      - ./:/build/source
      - .cache:/build/.cache
      - .config:/build/.config
    environment:
      - NODE_ENV=develop
      - PORT=8080
      - HOST=server
      - DEBUG=start-server-and-test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:3000"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 2s
    networks:
      default:
        aliases:
          - server

#  # run tests
#  cypress:
#    image: cypress/included:9.5.0
#    working_dir: /source
#    volumes:
#      - ./:/source
#    command: run --config baseUrl=http://server:8080
#    depends_on:
#      server:
#        condition: service_healthy
#    networks:
#      - default
#
#  reports:
#    image: aemdesign/java-buildpack:jdk11
#    command: /bin/bash -l /build/source/scripts/generate-reports.sh
#    working_dir: /build/source
#    volumes:
#      - ./:/build/source
#    environment:
#      - NODE_ENV=develop
#      - PORT=8080
#      - HOST=server
#    depends_on:
#      cypress:
#        condition: service_completed_successfully
#    networks:
#      default:
#        aliases:
#          - reports

networks:
  default:
